#!/usr/bin/env bash
# Script to set up Nginx on ubuntu with a custom HTTP response header

# Update and install nginx
sudo apt-get update -y && sudo apt-get install -y nginx

# Add entry file and error files
mkdir -p /etc/nginx/html
echo "Hello World!" > /var/www/html/index.nginx-default.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx to include custom HTTP response header
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOL
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ = 404;
		add_header X-Served-By \$hostname;
	}
}
EOL'

# Restart Nginx, to apply changes
sudo systemctl restart nginx
