#!/usr/bin/env bash
# Script installs and configures HAProxy on Ubuntu to balance traffic between
# web-01 and web-02

# Update and install HAProxy
sudo apt-get update -y && sudo apt-get install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg << EOL
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon


defaults
	log	global
	mode	http
	option	httplog
	option dontlognull
	timeout	connect	5000
	timeout client	50000
	timeout server	50000
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http

frontend main
	bind *:80
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 335953-web-01
	server 335953-web-02

listen stats
	bind *:8080
	stats enable
	stats uri /stats
	stats refresh 10s
EOL'

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
