#!/usr/bin/env bash
# Ensure Nginx is running & listens on port 80 of all servers active IPv4 IPs.
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
