#!/usr/bin/env bash
# This script displays "Best School" 9 times and "Hi" once
string="Best School"
i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 8 ]; then
		echo "Hi"
	else
		echo "$string"
	fi
	((i++))
done
