#!/usr/bin/env bash
# This script displays "Best School" 9 times and "Hi" once
string="Best School"
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo "$string"
		echo "Hi"
	else
		echo "$string"
	fi
	((i++))
done
