#!/usr/bin/env bash
# This script displays "bad luck", "good luck" and "Best School"
# based on conditions.
string1="bad luck"
string2="good luck"
string3="Best School"
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "$string1"
	elif [ $i -eq 8 ]; then
		echo "$string2"
	else
		echo "$string3"
	fi
	((i++))
done
