#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# and some custom strings based on condition.
string1="bad luck from China"
string2="bad luck from Japan"
string3="bad luck from Italy"
i=1
while [ $i -le 20 ]; do
	case $i in
		4)
			echo "$i"
			echo "$string1"
			;;
		9)
			echo "$i"
			echo "$string2"
			;;
		17)
			echo "$i"
			echo "$string3"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
