#!/usr/bin/env bash
# The script lists files of the current directory
for file in *; do
	if [ ! -d "$file" ] && [ "$file" != ".*" ] && [[ "$file" == *-* ]]; then
		filename=$(echo "$file" | cut -d'-' -f2-)
		echo "$filename"
	fi
done
