#!/usr/bin/env bash
# Script to check if apache is running and start it if not running
# docker exec -it e69b90e5445f /bin/bash
# Inside the container
# Check if apache2 is running
service apache2 status
# Start apache2 since it was not running
service apache2 start
