#!/usr/bin/env bash
# Script to reload gunicorn service with no downtime

# Get the Gunicorn master process ID
MASTER_PID=$(ps aux | grep gunicorn | grep ' Ss' | awk '{print $2}')

if [ -z "$MASTER_PID" ]; then
        exit 1
fi

# Send SIGHUP signal to the master process ti reload Gunicorn gracefully
kill -HUP "$MASTER_PID"
