#!/usr/bin/env bash
# Script to reload gunicorn service with no downtime

# Get the Gunicorn master process ID
# MASTER_PID=$(ps aux | grep gunicorn | grep ' Ss' | awk '{print $2}')
# MASTER_PID=$(pgrep -f 'gunicorn.* -b' | head -n 1)
MASTER_PID=$(ps auxf | awk '/gunicorn/ && / Ss/ {print $2}')

if [ -z "$MASTER_PID" ]; then
        exit 1
fi

# Send SIGHUP signal to the master process ti reload Gunicorn gracefully
kill -HUP "$MASTER_PID"
